[package]
name = "corrow-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
la-arena = "0.3.1"
lang-c = "0.15.1"
